<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-4NU9KSS" failures="3" tests="5" name="AccountRegistrationTest" time="104.947" errors="0" timestamp="2025-09-24T13:35:20 IST">
  <testcase classname="testcases.Tc_003Logindatadriventestcase" name="login" time="2.4"/>
  <testcase classname="testcases.Tc_003Logindatadriventestcase" name="login" time="31.073">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Tc_003Logindatadriventestcase.login(Tc_003Logindatadriventestcase.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="testcases.Tc_003Logindatadriventestcase" name="login" time="31.69">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Tc_003Logindatadriventestcase.login(Tc_003Logindatadriventestcase.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="testcases.Tc_003Logindatadriventestcase" name="login" time="31.712">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testcases.Tc_003Logindatadriventestcase.login(Tc_003Logindatadriventestcase.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="testcases.Tc_003Logindatadriventestcase" name="login" time="2.269"/>
</testsuite> <!-- AccountRegistrationTest -->
