<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="4" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-04T23:49:20 IST" name=" Master suite" finished-at="2025-10-04T23:51:14 IST" duration-ms="114247">
    <groups>
      <group name="regression">
        <method signature="Tc_001AccountRegistrationtest.Testregistration()[pri:0, instance:testcases.Tc_001AccountRegistrationtest@510f3d34]" name="Testregistration" class="testcases.Tc_001AccountRegistrationtest"/>
        <method signature="Tc_002Accountlogin.testlogin()[pri:0, instance:testcases.Tc_002Accountlogin@fa4c865]" name="testlogin" class="testcases.Tc_002Accountlogin"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="Tc_002Accountlogin.testlogin()[pri:0, instance:testcases.Tc_002Accountlogin@fa4c865]" name="testlogin" class="testcases.Tc_002Accountlogin"/>
      </group> <!-- sanity -->
      <group name="Datadriven">
        <method signature="Tc_003Logindatadriventestcase.login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testcases.Tc_003Logindatadriventestcase@3bd82cf5]" name="login" class="testcases.Tc_003Logindatadriventestcase"/>
      </group> <!-- Datadriven -->
      <group name="master">
        <method signature="Tc_001AccountRegistrationtest.Testregistration()[pri:0, instance:testcases.Tc_001AccountRegistrationtest@510f3d34]" name="Testregistration" class="testcases.Tc_001AccountRegistrationtest"/>
        <method signature="Tc_002Accountlogin.testlogin()[pri:0, instance:testcases.Tc_002Accountlogin@fa4c865]" name="testlogin" class="testcases.Tc_002Accountlogin"/>
      </group> <!-- master -->
    </groups>
    <test started-at="2025-10-04T23:49:20 IST" name="test" finished-at="2025-10-04T23:51:14 IST" duration-ms="114247">
      <class name="testcases.Tc_002Accountlogin">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:testcases.Tc_002Accountlogin@fa4c865]" started-at="2025-10-04T23:49:29 IST" name="setup" finished-at="2025-10-04T23:49:31 IST" duration-ms="2196" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testlogin()[pri:0, instance:testcases.Tc_002Accountlogin@fa4c865]" started-at="2025-10-04T23:49:31 IST" name="testlogin" finished-at="2025-10-04T23:49:33 IST" duration-ms="1527" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testlogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testcases.Tc_002Accountlogin@fa4c865]" started-at="2025-10-04T23:49:33 IST" name="teardown" finished-at="2025-10-04T23:49:33 IST" duration-ms="302" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcases.Tc_002Accountlogin -->
      <class name="testcases.Tc_001AccountRegistrationtest">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:testcases.Tc_001AccountRegistrationtest@510f3d34]" started-at="2025-10-04T23:49:20 IST" name="setup" finished-at="2025-10-04T23:49:26 IST" duration-ms="5889" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Testregistration()[pri:0, instance:testcases.Tc_001AccountRegistrationtest@510f3d34]" started-at="2025-10-04T23:49:26 IST" name="Testregistration" finished-at="2025-10-04T23:49:29 IST" duration-ms="2368" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testregistration -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testcases.Tc_001AccountRegistrationtest@510f3d34]" started-at="2025-10-04T23:49:29 IST" name="teardown" finished-at="2025-10-04T23:49:29 IST" duration-ms="411" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcases.Tc_001AccountRegistrationtest -->
      <class name="testcases.Tc_003Logindatadriventestcase">
        <test-method is-config="true" signature="setup(java.lang.String,java.lang.String)[pri:0, instance:testcases.Tc_003Logindatadriventestcase@3bd82cf5]" started-at="2025-10-04T23:49:33 IST" name="setup" finished-at="2025-10-04T23:49:35 IST" duration-ms="2329" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testcases.Tc_003Logindatadriventestcase@3bd82cf5]" started-at="2025-10-04T23:49:37 IST" name="login" data-provider="LoginData" finished-at="2025-10-04T23:49:39 IST" duration-ms="2396" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[fun123@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testcases.Tc_003Logindatadriventestcase@3bd82cf5]" started-at="2025-10-04T23:49:39 IST" name="login" data-provider="LoginData" finished-at="2025-10-04T23:50:10 IST" duration-ms="31254" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[manideep@909]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Tc_003Logindatadriventestcase.login(Tc_003Logindatadriventestcase.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testcases.Tc_003Logindatadriventestcase@3bd82cf5]" started-at="2025-10-04T23:50:11 IST" name="login" data-provider="LoginData" finished-at="2025-10-04T23:50:41 IST" duration-ms="30694" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[fun22@yopmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Tc_003Logindatadriventestcase.login(Tc_003Logindatadriventestcase.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testcases.Tc_003Logindatadriventestcase@3bd82cf5]" started-at="2025-10-04T23:50:41 IST" name="login" data-provider="LoginData" finished-at="2025-10-04T23:51:12 IST" duration-ms="30667" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[fun33@yopmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at testcases.Tc_003Logindatadriventestcase.login(Tc_003Logindatadriventestcase.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:testcases.Tc_003Logindatadriventestcase@3bd82cf5]" started-at="2025-10-04T23:51:12 IST" name="login" data-provider="LoginData" finished-at="2025-10-04T23:51:14 IST" duration-ms="1646" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Fun143@yopmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testcases.Tc_003Logindatadriventestcase@3bd82cf5]" started-at="2025-10-04T23:51:14 IST" name="teardown" finished-at="2025-10-04T23:51:14 IST" duration-ms="248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testcases.Tc_003Logindatadriventestcase -->
    </test> <!-- test -->
  </suite> <!--  Master suite -->
</testng-results>
